### ISSUE TITLE
_content not found (error 404)

### ISSUE THREAD

**Issue by dsx75** [lolochristen/OpenLayers.Blazor#69]
Hello,

I'm trying to test your NuGet 2.0.1 package in a Blazor Interactive Server 8.0 project, but I'm getting these errors (in a web browser) when running the application:

GET http://localhost:5555/_content/OpenLayers.Blazor/OpenLayers.Blazor.css net::ERR_ABORTED 404 (Not Found)
        
GET http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js net::ERR_ABORTED 404 (Not Found) blazor.web.js:1 

[2024-07-24T07:36:22.963Z] Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at OpenLayers.Blazor.Map.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Any ideas, please?

**Comment by dsx75** [comment]
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
      Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at OpenLayers.Blazor.Map.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '0oeVIAsHHqt7MCjCf1MSVNAj3WA6e57vsNRUjB6YlsU'.
      Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at OpenLayers.Blazor.Map.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
      Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5555/_content/OpenLayers.Blazor/openlayers_interop.js
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at OpenLayers.Blazor.Map.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by dsx75** [comment]
I created a brand-new clean Blazor Server project and everything seems to be working fine.

So, my 404 error must be retard to my existing code or my settings. 

I am so sorry about the false alarm.

Please, close this issue.
