### ISSUE TITLE
When I use OpenLayers in Blazor Hybrid WPF, I encounter the following error.

### ISSUE THREAD

**Issue by protossman** [lolochristen/OpenLayers.Blazor#7]
Uncaught (in promise) Error: System.Text.Json.JsonException: The JSON value could not be converted to System.Double. Path: $.Y | LineNumber: 0 | BytePositionInLine: 9.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
   at System.Text.Json.Utf8JsonReader.GetDouble()
   at System.Text.Json.Serialization.Converters.DoubleConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at endInvokeDotNetFromJS (https://0.0.0.0/_framework/blazor.webview.js:1:3531)
    at https://0.0.0.0/_framework/blazor.webview.js:1:40711
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:38538)

**Comment by lolochristen** [comment]
Hi, Your error/exception does not indicate that it has something directly to do with the OpenLayers.Blazor component. I have not recreated a WPF hybrid scenario to verify it myself but. I have made a  test app using MAUI in Blazor mode (branch feature/maui-demo) without any problems. Can you tell me how you have integrated the component into WPF?

**Comment by protossman** [comment]
Thank you for your response. I have resolved the issue by adjusting the latitude and longitude parameters in the data.

**Comment by protossman** [comment]
I would like to inquire if it is currently possible to obtain the zoom level and the bounding coordinates of a map view.

**Comment by lolochristen** [comment]
Glad, you could solve the problem. The zoom level is already a bidirectional parameter. The bound coordinates of the map view so far are not. It sounds to me like a useful feature and I added it. It's currently on the branch feature/visible-extent. The Map component contains a new parameter VisibleExtent and syncs bi-directional. I'll release it when testing is successful.
