### ISSUE TITLE
Setting ScaleLineUnit=ScaleLineUnit.None on Map causes OL to thrown Invalid Units Error

### ISSUE THREAD

**Issue by Horndev** [lolochristen/OpenLayers.Blazor#74]
If ScaleLineUnit=ScaleLineUnit.None is added to the map, there is an unhandled javascript error "Invalid Units", and the map does not load.

```
Uncaught Error Error: Invalid units
    at updateElement_ (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:444:132043)
    at render (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:444:134112)
    at dispatchEvent (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:2477)
    at renderFrame_ (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:190257)
    at animationDelay_ (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:188235)
    --- requestAnimationFrame ---
    at render (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:188619)
    at handleSizeChanged_ (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:185480)
    at dispatchEvent (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:2477)
    at notify (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:4983)
    at set (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:5297)
    at setSize (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:190748)
    at updateSize (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:191473)
    at handleTargetChanged_ (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:187160)
    at dispatchEvent (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:2477)
    at notify (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:4983)
    at set (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:5297)
    at setProperties (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:5351)
    at Bh (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor.Demo.Server\wwwroot\lib\openlayers\dist\ol.min.js:1:179868)
    at MapOL (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor\wwwroot\openlayers_interop.js:194:16)
    at MapOLInit (C:\Users\steve\source\repos\OpenLayers.Blazor\src\OpenLayers.Blazor\wwwroot\openlayers_interop.js:4:21)
```

**Comment by lolochristen** [comment]
PR #75 will fix this.
