### ISSUE TITLE
Force reload cause exception

### ISSUE THREAD

**Issue by BuddhaCodes** [lolochristen/OpenLayers.Blazor#95]
If I am on a page with the map, and change the language of the site lets say, forcing a reload for it to apply the changes an exceptions pops up [chromium] [INFO:CONSOLE(1)] "Exceptions were encountered while disposing components. (JS object instance with ID 1 does not exist (has it been disposed?).
[chromium] Error: JS object instance with ID 1 does not exist (has it been disposed?).

**Comment by DFHjartarson** [comment]
I am running into similar issues when I do a force reload:
~~~
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at OpenLayers.Blazor.Map.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass93_0.<<Dispose>g__HandleAsyncExceptions|0>d.MoveNext()
~~~

I've created a minimal reproduction of the issue that can be found here:
https://github.com/DFHjartarson/openLayersBlazor_errorRepro

**Comment by BuddhaCodes** [comment]
@DFHjartarson Any workarounds?

**Comment by BuddhaCodes** [comment]
@DFHjartarson Mate one workaround I found was to create a "Reload page", it receives an address as parameter, I navigate normally to that page, then, on that page do the force reload navigation to the other page I want to go.

`@page "/reload/{Address?}"
@inject NavigationManager Navigation
@code {

	[Parameter]
	public string? Address { get; set; }

	protected override void OnInitialized()
	{
		if(string.IsNullOrEmpty(Address))
		{
			Navigation.NavigateTo("/", true);
		}
		else
		{
			var decodedAddress = Uri.UnescapeDataString(Address);
			Navigation.NavigateTo($"/{decodedAddress}", true);
		}
	}
}
`

Consider that some routes are complex like "/page1/section1" in this case you need to encode the url

**Comment by lolochristen** [comment]
Using latest release 2.4.0 with build and fixes for .NET 9 seems to solve your issues.
